name: bio_pipeline_env
channels:
  - conda-forge
  - defaults
dependencies:
  - nextflow
  - openjdk=11
  - fastqc
  - bwa
  - samtools
  - bedtools
  - minimap2
  - mosdepth
  - sniffles
  - nanopolish
  - ont-fast5-api
  - biopython

