name: bio_pipeline_env
channels:
  - bioconda
  - conda-forge
dependencies:
  - openjdk=11
  - nextflow
  - nanoplot
  - minimap2
  - samtools
  - bedtools
  - mosdepth
  - modbam2bed
  - sniffles
  - cuteSV
  - clair3
  - svanna-cli
  - longphase
  - svanna-cli
  - perl
  - jannovar-cli
